#!/bin/sh
### BEGIN INIT INFO
# Provides:          radio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start radiotag-radio components
### END INIT INFO
# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo "Starting radio"
    /usr/sbin/service radiotag-piface start
    /usr/sbin/service radiotag-radio start
    echo "."
    ;;
  stop)
    echo "Stopping radio "
    /usr/sbin/service radiotag-radio stop
    /usr/sbin/service radiotag-piface stop
    echo "."
    ;;
  restart)
    echo "Restarting radio"
    /usr/sbin/service radiotag-piface restart
    /usr/sbin/service radiotag-radio restart
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
