#!/bin/sh
### BEGIN INIT INFO
# Provides:          radiotag-radio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple radio with radiotag
# Description:       Simple radio with radiotag
### END INIT INFO
# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
#export LOG_LEVEL=debug
export BBC_SERVICES_URL=https://bbc-services-api.herokuapp.com
export TAG_SERVICE_URL=http://tag.test.bbc.madebykite.com/

# Must be a valid filename
NAME=radiotag-radio
PIDFILE=/var/run/radiodan/$NAME.pid
DIR=/home/pi/radiotag-radio
#This is the command to be run, give the full pathname
DAEMON=/home/pi/radiotag-radio/bin/radio
DAEMON_OPTS="/tmp/radiotag-radio.sock"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo -n "Starting daemon: "$NAME
    start-stop-daemon --start --quiet --background --no-close --make-pidfile --pidfile $PIDFILE --chdir $DIR --exec $DAEMON -- $DAEMON_OPTS > /var/log/$NAME.log 2>&1
    echo "."
    ;;
  stop)
    echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    rm $PIDFILE
    echo "."
    ;;
  restart)
    echo -n "Restarting daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
